name: mad_lib
description: A polymer Mad Lib app that takes the users input for missing words and places them into a pre-generated story.
dependencies:
  polymer: any
transformers:
- polymer:
    entry_points: web/index.html
